In [74]:
import os

In [75]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [76]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [77]:
df=pd.read_csv(r'C:\Users\mayur\OneDrive\Desktop\data science training\project\medical\data\clean_medical.csv')

In [78]:
df

,Unnamed: 0,Gender,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease,Age,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate
0,0,1,0,1,1,0,1,23,17.5,102,177,161,88
1,1,1,0,1,2,1,2,69,31.1,118,256,147,92
2,2,2,1,1,1,0,1,61,31.3,114,206,193,74
3,3,2,0,1,3,0,1,47,23.9,105,162,253,68
4,4,1,0,2,2,0,1,47,28.3,148,121,280,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,1,0,1,2,0,3,49,27.1,177,183,268,59
9996,9996,1,0,2,2,1,3,84,29.2,142,215,145,77
9997,9997,1,0,1,1,1,3,41,22.8,177,265,133,71
9998,9998,1,0,1,1,1,2,55,29.0,126,241,298,57
9999,9999,1,0,1,2,1,2,59,32.2,151,162,225,93

In [79]:
print(df['Disease'].value_counts())

Disease
1    6329
3    1771
2    1453
4     232
5     215
Name: count, dtype: int64

In [80]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [81]:
x=df.drop('Disease',axis=1)

In [82]:
y=df[['Disease']]

In [83]:
x

,Gender,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Age,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate
0,1,0,1,1,0,23,17.5,102,177,161,88
1,1,0,1,2,1,69,31.1,118,256,147,92
2,2,1,1,1,0,61,31.3,114,206,193,74
3,2,0,1,3,0,47,23.9,105,162,253,68
4,1,0,2,2,0,47,28.3,148,121,280,84
...,...,...,...,...,...,...,...,...,...,...,...
9995,1,0,1,2,0,49,27.1,177,183,268,59
9996,1,0,2,2,1,84,29.2,142,215,145,77
9997,1,0,1,1,1,41,22.8,177,265,133,71
9998,1,0,1,1,1,55,29.0,126,241,298,57
9999,1,0,1,2,1,59,32.2,151,162,225,93

In [84]:
y

      Disease
0           1
1           2
2           1
3           1
4           1
...       ...
9995        3
9996        3
9997        3
9998        2
9999        2

[10000 rows x 1 columns]

In [85]:
print(df["Disease"].unique())

[1 2 3 4 5]

In [86]:
print(df["Disease"].value_counts())

Disease
1    6329
3    1771
2    1453
4     232
5     215
Name: count, dtype: int64

In [87]:
print(df["Disease"].value_counts())

Disease
1    6329
3    1771
2    1453
4     232
5     215
Name: count, dtype: int64

In [88]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [89]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
from sklearn.svm import SVC
sv=SVC()
sv.fit(x_train,y_train)
print("svc training",sv.score(x_train,y_train))
print("svc testing",sv.score(x_test,y_test))

c:\Users\mayur\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

svc training 0.63125
svc testing 0.6395

In [90]:
log=LogisticRegression()
log.fit(x_train,y_train)
print("log training",log.score(x_train,y_train))
print("log testing",log.score(x_test,y_test))

log training 0.630625
log testing 0.6395

c:\Users\mayur\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\mayur\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [91]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(
    max_depth=5,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)

dt.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=5, min_samples_leaf=5, min_samples_split=10,
                       random_state=42)

In [92]:
# from sklearn.tree import DecisionTreeClassifier
# # x,y=loan_approved(return_X_y=True)
# x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
# dt=DecisionTreeClassifier()
# dt.fit(x_train,y_train)

In [93]:
print("dt training",dt.score(x_train,y_train))
print("dt testing",dt.score(x_test,y_test))

dt training 0.667375
dt testing 0.6555

In [94]:
import joblib
joblib.dump(dt,"dt_load.lb")

['dt_load.lb']

In [95]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    min_samples_split=10,
    min_samples_leaf=5,
    class_weight='balanced',
    random_state=42
)

In [96]:

rfc.fit(x_train, y_train)

print("Train:", rfc.score(x_train, y_train))
print("Test:", rfc.score(x_test, y_test))

c:\Users\mayur\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Train: 0.687625
Test: 0.64

In [97]:
import joblib
joblib.dump(rfc,"rfc_load.lb")

['rfc_load.lb']

In [98]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(x_train, y_train)

print("Train:", rf.score(x_train, y_train))
print("Test:", rf.score(x_test, y_test))

c:\Users\mayur\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Train: 1.0
Test: 0.6745

In [99]:
print(model.classes_)

[1 2 3 4 5]

In [102]:
import joblib

model = joblib.load(r"C:\Users\mayur\OneDrive\Desktop\data science training\project\medical\model\rfc_load.lb")
print(model.classes_)

[1 2 3 4 5]